### ISSUE TITLE
lists.staffslug.org.uk not working

### ISSUE THREAD

**Issue by gwestwood** [lugorguk/lug.org.uk-website#112]
From Travis CI report: External link http://lists.staffslug.org.uk/mailman/listinfo/staffslug failed.

Also, from http://staffslug.org.uk:

> A new web site for a new year is coming soon!
> 
> We did have a WordPress site here but it had very little content and even then was out of date so it didn't matter about moving it when we moved servers.
> 
> The Staffordshire Linux User Group was formed in 1999 by Dave Roberts and Mark Leese and is currently undergoing a shake up of added locations to have meetings, volunteer involvement in its running and new ideas to achieve our goals.
> 
> Please visit this web site soon, we hope to have something more by at the latest the middle of February.
> 
> The mailing list should be up again very shortly, just in the process of piecing it back together now.

So, either it is dead, or the website update is very delayed.

**Comment by Lantizia** [comment]
It is very delayed - website content should change within the next week.

A bunch of us are resurrecting things probably within the next month, mailing list too.  

I know the site has said that for a while (since 2014) but that reboot just didn't take.  This reboot (in 2019) is going to be very different and we're taking sign-ups already.

This github issue has been brought to my attention by one of the older LUG members as we've been talking about the reboot :)

Keep the issue open, I'll post an update here shortly.

**Comment by JonTheNiceGuy** [comment]
New website is there now! Huzzah! The mailing list hasn't been sorted yet, but I just wanted to add an update to this "issue" while I had some time :)

**Comment by Lantizia** [comment]
Yeah Mailman 3 is a pain :)  https://lists.staffslug.org.uk should at least show something.  The main thing I've yet to get working is the HyperKitty bit, but the mailing list bit at least functions properly.  I'll probably turn the old staffslug@staffslug.org.uk address in to general@lists.staffslug.org.uk and import all the old archived past messages into the new system.

**Comment by JonTheNiceGuy** [comment]
> https://lists.staffslug.org.uk should at least show something.

![image](https://user-images.githubusercontent.com/228671/63440402-a73be600-c427-11e9-826b-ec1eec5df585.png)

Would it be more convenient to host the mailing list at lug.org.uk? - https://mailman.lug.org.uk

**Comment by Lantizia** [comment]
That's just because I'm in the middle of rolling back snapshots on the VM which Mailman 3 is running on - trying out different things before it goes production ready.

I did say you'd get "something" :P

You probably don't even see the same thing even now.

**Comment by Lantizia** [comment]
This can be closed off now, lists and site are functional again.
