### ISSUE TITLE
Updates to Staffordshire Linux User Group entry

### ISSUE THREAD

**Issue by Lantizia** [lugorguk/lug.org.uk-website#116]
**The below information can be validated by contacting info@staffslug.org.uk if required.**

Could someone update the details for Staffordshire Linux User Group...

https://lug.org.uk/lugs/West-Midlands/Staffordshire/

**Website:** https://staffslug.org.uk/                 (notice https:// now)
**Established:** 1999/03
**Entry last updated:** 2019/08                        (new date)
**Status:** Active
**Region:** West-Midlands
**Contact/LUGmaster:** info@staffslug.org.uk (this can be both the text and also mailto: link)
**Mailing list:** https://lists.staffslug.org.uk (that base URL redirects people to the right suffix for mailman 3 - which is different to the older mailman 2 that it points to now - it's also now on https:// too)

Also the lug.org.uk hosted 'staffs' mailing list can be deleted/hidden (or whatever you do if they go unused) if you like, as...
**a)** it's barely seen any use since about 2008, mostly because the LUG has ran their own on one server or another since 2005.
**b)** we've got an archive of all the messages from past mailing lists (including the lug.org.uk one) here...
    https://lists.staffslug.org.uk/mailman3/hyperkitty/list/staffslug@staffslug.org.uk
    https://lists.staffslug.org.uk/mailman3/hyperkitty/list/staffs@mailman.lug.org.uk/

**Comment by JonTheNiceGuy** [comment]
Updates made as requested. I'll forward the request to have the staffs mailing list archived, as I'm not sure what process we need to follow for that.
