### ISSUE TITLE
Google Map Pin Location for StaffsLUG

### ISSUE THREAD

**Issue by Lantizia** [lugorguk/lug.org.uk-website#117]
Hey,

Just a tiny request, any chance on this page...

http://lugs.org.uk/lugs/West-Midlands/Staffordshire/

Can the Google Map red "pin" be moved to... 53.003, -2.273 (which is 53.003°N 2.273°W... the same co-ordinates stated for "Keele University" on Wikipedia).

It's just that despite our name "**Staffordshire** Linux User Group" we've started to talk to and work with other near by LUGs and have realised we're better of serving the northern end of the county more.  As a result both our regular workshops and socials all take place at Keele.

At the moment the red pin has us looking like we're in the middle of a field :)

We've put more information about this in a little blog post... https://staffslug.org.uk/ideas-on-coverage/

Thanks

**Comment by JonTheNiceGuy** [comment]
Done! :)
