### ISSUE TITLE
Coventry LUG mailing list URL does not work.

### ISSUE THREAD

**Issue by JonTheNiceGuy** [lugorguk/lug.org.uk-website#126]
Website seems to have last been updated 2017, and is very broken. Website Mailing list URL does not reply, lug list mailing list URL is invalid.

Needs follow-up.

**Comment by gwestwood** [comment]
Found correct URL for the Coventry LUG Mailing list and updated it: https://covlug.org.uk/pmwiki.php?n=Main.MailingLists

**Comment by gwestwood** [comment]
Found correct URL for the Coventry LUG Mailing list and updated it: https://covlug.org.uk/pmwiki.php?n=Main.MailingLists
