### ISSUE TITLE
Kent Lug

### ISSUE THREAD

**Issue by danbuntu** [lugorguk/lug.org.uk-website#136]
Hello

Kent Lug is inactive. 
Could please mark it so and remove the link to the website

**Comment by gwestwood** [comment]
Thanks @danbuntu.  I'm going to give it a few days for other Lugmasters to respond, but will then apply your update as requested.

**Comment by gwestwood** [comment]
I've removed the website link and your contact details, and changed the status to inactive.  These changes will be merged in a day or two.

**Comment by gwestwood** [comment]
Merged and Kent is now showing as inactive with your details and the website removed.
