### ISSUE TITLE
Isle of Man Linux User Group - no changes needed

### ISSUE THREAD

**Issue by isleofmandan** [lugorguk/lug.org.uk-website#139]
Details are all OK. We're not very active these days, but when I suggested winding up the group a few years ago everyone protested! Currently all activity is online. New members are always welcome, and real life meets can be arranged as needed.
Thank you.

**Comment by gwestwood** [comment]
I've updated the Last Updated date. This will be merged in the next day or two.

**Comment by gwestwood** [comment]
Merged and change is live.
