### ISSUE TITLE
Remove phpwm mailing list

### ISSUE THREAD

**Issue by DavidGoodwin** [lugorguk/lug.org.uk-website#142]
Hi -

PHPWM - it was a PHP user group for people around Birmingham. It's not listed on your LUGS page (as it's not a LUG). But I'm pretty sure lug.org.uk hosts the phpwm mailing list, which has not been used for some time (a number of years).

You can also remove me (david@codepoets.co.uk) from the admin mailing list if you so wish as I don't think I'm an admin for any other LUG like groups.

TIA....

David

**Comment by gwestwood** [comment]
@DavidGoodwin Thanks, I'll get onto that in a few days once everyone's had a chance to submit their updates so that I can do them all at once.

**Comment by gwestwood** [comment]
@DavidGoodwin Sorry, I realised later that, as you said, it's relating just to a mailing list, not an entry on the rest of the website.  I've forwarded the information to our Admin email address so we can get onto that, but will close this ticket now.
