### ISSUE TITLE
Shropshire Linux group 

### ISSUE THREAD

**Issue by g0cer** [lugorguk/lug.org.uk-website#143]
Shropshire Linux group ok except location showing in Scotland accurate location is 
The cock hotel, Wellington, Telford , Shropshire,  tf1 2dl

**Comment by gwestwood** [comment]
@g0cer Thanks.  Yeah I've noticed a number of co-ordinates seem to be way off.  I'll find the latitude and longitude of that location and update it as well as the update date.

**Comment by gwestwood** [comment]
I've changed the co-ordinates to be that of the pub, although they weren't far out despite what the map display would suggest, so I think that the map is broken for all the LUGs.  I'll merge the changes in a day or two.

**Comment by g0cer** [comment]
Loos good thanks for your work GavinDaveSent from my iPhoneOn 13 Jan 2024, at 17:24, Gavin Westwood ***@***.***> wrote:﻿
I've changed the co-ordinates to be that of the pub, although they weren't far out despite what the map display would suggest, so I think that the map is broken for all the LUGs.  I'll merge the changes in a day or two.

**Comment by gwestwood** [comment]
Merged and change is live.
