### ISSUE TITLE
Berkshire & Thames Valley ("Silicon Corridor") Details Correct

### ISSUE THREAD

**Issue by xplora1a** [lugorguk/lug.org.uk-website#146]
Thanks GAvin
SCLUG details are correct
Stuart

**Comment by gwestwood** [comment]
Thanks, I have updated the Lasted Updated date.  I have also altered the mailing list URL as that was redirecting to the whole list of mailing lists on Mailman, and instead I have put https://mailman.lug.org.uk/mailman/listinfo/sclug.

**Comment by gwestwood** [comment]
Merged and change is live.
