### ISSUE TITLE
Is Brighton LUG active?

### ISSUE THREAD

**Issue by rozkerim** [lugorguk/lug.org.uk-website#158]
Last updated: 2010/10
The map shows a random place and domain name of contact email is not registered.

**Comment by gwestwood** [comment]
Thanks @rozkerim .  The map seems to be a bit broken, we need to look at that, and indeed we did suspect that Brighton was no longer active (#127) - we'll be looking to flag the inactive ones soon to make sure the list of LUGs reflects those that are active.

**Comment by gwestwood** [comment]
Closing ticket as duplicate.
