### ISSUE TITLE
Note: Old list duplicated onto Ubuntu Wiki

### ISSUE THREAD

**Issue by gwestwood** [lugorguk/lug.org.uk-website#33]
It's worth noting that https://wiki.ubuntu.com/UKTeam/UKLugMembers has an old list which looks like it was copied in 2006 and had some updates between then and 2013.  We should check if there are any changes that we should query with the lugmaster of that lug and possibly suggest when our new site is live that they remove that page and point it at our updated one?

**Comment by popey** [comment]
Fixed

**Comment by gwestwood** [comment]
If we need to refer to any updates that were added to that page, the old page can be seen at https://wiki.ubuntu.com/UKTeam/UKLugMembers?action=recall&rev=79 - although since this was edited last in 2013, they are probably all out of date too.
