### ISSUE TITLE
Timeout on URL: pgp.mit.edu:11371

### ISSUE THREAD

**Issue by JonTheNiceGuy** [lugorguk/lug.org.uk-website#35]
Origin: https://github.com/lugorguk/lug.org.uk-website/blob/800e50309d2f7b8993d15fc7f2cf6fb2346145ee/admins.md

Name: Alasdair Kergon

**Comment by diocles** [comment]
One alternative URL on a site running the same software:

https://pgp.surfnet.nl/pks/lookup?op=get&search=0x28f50196c43802eb

Not commenting on the trust implications of this...

**Comment by JonTheNiceGuy** [comment]
For consistency we could use keyserver.ubuntu.com? That tends to be considered as trusted?
