### ISSUE TITLE
Certificate Error: keys.alderwick.co.uk

### ISSUE THREAD

**Issue by JonTheNiceGuy** [lugorguk/lug.org.uk-website#36]
Origin: https://github.com/lugorguk/lug.org.uk-website/blob/800e50309d2f7b8993d15fc7f2cf6fb2346145ee/admins.md

Name: Gavin Westwood

**Comment by gwestwood** [comment]
See #69 for patch.

**Comment by JonTheNiceGuy** [comment]
Closed by #69
