### ISSUE TITLE
404 on link: http://tyneside.lug.org.uk/mailman/listinfo

### ISSUE THREAD

**Issue by JonTheNiceGuy** [lugorguk/lug.org.uk-website#41]
Origin: https://github.com/lugorguk/lug.org.uk-website/blob/800e50309d2f7b8993d15fc7f2cf6fb2346145ee/_posts/0000-01-01-Tyneside%20(Newcastle).md

**Comment by gwestwood** [comment]
Changes requested by Derek Frost on 22/05/2018 covering this.  I've created a patch.
