### ISSUE TITLE
Certificate Error: https://www.rosslug.org.uk [Suspend until 2019-05-02 pending fix]

### ISSUE THREAD

**Issue by JonTheNiceGuy** [lugorguk/lug.org.uk-website#44]
Origin: https://github.com/lugorguk/lug.org.uk-website/blob/800e50309d2f7b8993d15fc7f2cf6fb2346145ee/_posts/0000-01-01-Rossendale%20LUG.md

Website and Mailing list fields both refer to this domain (using HTTP). Automatic redirection occurs and certificate expired August 2018.

**Comment by gwestwood** [comment]
Site users HTTP Strict Transport Security (HSTS) so plain HTTP is not possible.  We should remove this LUG as the mailing list is also inaccessible, being on the same website.

**Comment by JonTheNiceGuy** [comment]
Twitter DM sent to (believed) RossLUG lugmaster. Awaiting response.

**Comment by JonTheNiceGuy** [comment]
Slightly reduced version of response:
> The LUG is dormant at the mo. Although that tells me the letsencrypt auto-renewal isn't working. I'll jump on asap and fix it. Ta.

Suspension on issue (nudge me to re-approach if this turns into more than 1 week!), pending fix.

**Comment by JonTheNiceGuy** [comment]
Issue resolved. Cert renewed.
