### ISSUE TITLE
404 in link: http://www.belfastlinux.org/wiki/Mailing_list

### ISSUE THREAD

**Issue by JonTheNiceGuy** [lugorguk/lug.org.uk-website#45]
Origin: https://github.com/lugorguk/lug.org.uk-website/blob/800e50309d2f7b8993d15fc7f2cf6fb2346145ee/_posts/0000-01-01-Belfast.md

**Comment by gwestwood** [comment]
URL for the mailing list is http://www.belfastlinux.org/list.html.
This was resolved in #32
