### ISSUE TITLE
Timeout on URL: http://dundeelug.org.uk/

### ISSUE THREAD

**Issue by JonTheNiceGuy** [lugorguk/lug.org.uk-website#48]
Origin: https://github.com/lugorguk/lug.org.uk-website/blob/800e50309d2f7b8993d15fc7f2cf6fb2346145ee/_posts/0000-01-01-Dundee%20%26%20Tayside.md

**Comment by gwestwood** [comment]
Domain dundeelug.org.uk - no valid DNS records

**Comment by gwestwood** [comment]
The mailing list is dead - last real post was in 2017.  Propose deletion.
