### ISSUE TITLE
404 on link: http://www.edlug.org.uk/list_faq.html

### ISSUE THREAD

**Issue by JonTheNiceGuy** [lugorguk/lug.org.uk-website#49]
Origin: https://github.com/lugorguk/lug.org.uk-website/blob/800e50309d2f7b8993d15fc7f2cf6fb2346145ee/_posts/0000-01-01-Edinburgh.md

**Comment by gwestwood** [comment]
EdLUG has a new URL: https://edlug.gitlab.io
The mailing list page is at https://edlug.gitlab.io/mailing-list/
