### ISSUE TITLE
Timeout on URL: http://nos-lug.org/

### ISSUE THREAD

**Issue by JonTheNiceGuy** [lugorguk/lug.org.uk-website#50]
Origin: https://github.com/lugorguk/lug.org.uk-website/blob/800e50309d2f7b8993d15fc7f2cf6fb2346145ee/_posts/0000-01-01-North%20of%20Scotland.md

**Comment by gwestwood** [comment]
Domain nos-lug.org is no longer registered.
I found a Blogspot site last posted to in 2012: https://nos-lug.blogspot.com
Ditto for what seems to have been their Twitter handle: https://twitter.com/NoS_LUG
LUG is dead, should be deleted.
