### ISSUE TITLE
Timeout on URL: http://orklug.org.uk/

### ISSUE THREAD

**Issue by JonTheNiceGuy** [lugorguk/lug.org.uk-website#51]
Origin: https://github.com/lugorguk/lug.org.uk-website/blob/800e50309d2f7b8993d15fc7f2cf6fb2346145ee/_posts/0000-01-01-Orkney.md

**Comment by gwestwood** [comment]
Domain orklug.org.uk is no longer registered.

**Comment by gwestwood** [comment]
No evidence that Orkney LUG still exists.  Propose deletion.
