### ISSUE TITLE
Timeout on URL: http://eglug.org.uk/

### ISSUE THREAD

**Issue by JonTheNiceGuy** [lugorguk/lug.org.uk-website#53]
Origin: https://github.com/lugorguk/lug.org.uk-website/blob/800e50309d2f7b8993d15fc7f2cf6fb2346145ee/_posts/0000-01-01-East%20Grinstead.md

**Comment by gwestwood** [comment]
The URL is now http://eg.lug.org.uk, but other details need to be changed too as Peter Jones set about reviving it in February 2019.
