### ISSUE TITLE
Timeout on URL: http://exeter.lug.org.uk

### ISSUE THREAD

**Issue by JonTheNiceGuy** [lugorguk/lug.org.uk-website#57]
Origin: https://github.com/lugorguk/lug.org.uk-website/blob/800e50309d2f7b8993d15fc7f2cf6fb2346145ee/_posts/0000-01-01-Exeter.md

**Comment by gwestwood** [comment]
From the mailing list and lack of website, I believe that this LUG is dead.

**Comment by JonTheNiceGuy** [comment]
Resolved on 5b8ba5a3ba330376e6a5b0ae67dde24fd5b5f43e
