### ISSUE TITLE
Timeout on URL: https://swinlug.org.uk

### ISSUE THREAD

**Issue by JonTheNiceGuy** [lugorguk/lug.org.uk-website#58]
Origin: https://github.com/lugorguk/lug.org.uk-website/blob/800e50309d2f7b8993d15fc7f2cf6fb2346145ee/_posts/0000-01-01-Swindon.md

**Comment by gwestwood** [comment]
Looks like it's just domain parking now.  The mailing list hasn't had a post since 2016, and most of the posts going back years are just spam.  LUG should be deleted.
