### ISSUE TITLE
404 on link: http://www.covlug.org.uk/mailinglist.html

### ISSUE THREAD

**Issue by JonTheNiceGuy** [lugorguk/lug.org.uk-website#59]
Origin: https://github.com/lugorguk/lug.org.uk-website/blob/800e50309d2f7b8993d15fc7f2cf6fb2346145ee/_posts/0000-01-01-Coventry.md

**Comment by gwestwood** [comment]
Still timing out.  The last Web Archive snapshot of it was in December 2018: http://web.archive.org/web/20181001000000*/http://www.covlug.org.uk
I suggest we remove the URL links and reach out to the Lugmaster list or see if they still have an IRC channel (as mentioned in the archived webpage) to work out if they are still active.

**Comment by gwestwood** [comment]
No evidence of a current Coventry LUG, so proposing deletion.

**Comment by JonTheNiceGuy** [comment]
I've reached out to someone who, only a year ago, was talking about the LUG being active, and pointed them at this issue. I'll see what happens...

**Comment by tadgy** [comment]
Hi.  I'm the LUGmaster for CovLUG.
I'm sorry for the lack of contact on this matter - I was unaware that the website had the wrong link to the mailing lists page of our website.  For some unknown reason I have no received any of the emails trying to make contact about this problem.

To correct the website, the URL for our mailing list page is:
http://www.covlug.org.uk/index.php?n=Members.MailingList

Regarding the availability of the website; the server which hosts the website occasionally has its connection go down.  This doesn't happen often, but you may have checked it during a period where it was offline.

I hope this helps sort the issues out and will keep us on your list of LUGs!
