### ISSUE TITLE
Storing email addresses on Github

### ISSUE THREAD

**Issue by gwestwood** [lugorguk/lug.org.uk-website#64]
Should we be storing Lugmaster email addresses here on Github?
What could we do otherwise to make them appear on the Lug website?
Are we able to remove them from all the history of commits on this repo?

**Comment by JonTheNiceGuy** [comment]
So, the only way I can see it working is to remove the whole repo, purge them and create a new repo. The only other thing worth doing would be to enforce that all Lugmasters must use <organiser|lugmaster|contact>@<lugname>.lug.org.uk and then rewrite them to use that.

Probably not a bad idea to do that *anyway*

**Comment by JonTheNiceGuy** [comment]
Another thing to bear in mind - we've been storing these email addresses in plaintext on the lug.org.uk site all along. Anyone who wants to peruse archive.org will find them...
