### ISSUE TITLE
Need inactive Lugs page and/or redirect

### ISSUE THREAD

**Issue by gwestwood** [lugorguk/lug.org.uk-website#73]
Need to set up or redirect URL for inactive lug message page (404 for current URL at http://www.lug.org.uk/lugs/inactive ).

**Comment by JonTheNiceGuy** [comment]
What is the purpose of this page? Is it what we redirect foo.lug.org.uk to when it's been wound up?

**Comment by gwestwood** [comment]
Yes.  See http://www.basset.lug.org.uk for instance.

**Comment by JonTheNiceGuy** [comment]
Fixed (eventually) in cba87a53
